# Generated by Django 4.2.1 on 2023-06-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientinrecipe',
            unique_together=set(),
        ),
    ]
